apiVersion: v2
name: cp
description: A Helm chart for Kubernetes
type: application
version: "{{CHART_VERSION}}"
appVersion: "1.0.0"
dependencies:
  - name: cp-ui-chart
    repository: "https://pongsathorn-ph.github.io/cp-ui/helm-chart/"
    version: "{{DEPENDENCY_UI_VERSION}}"