apiVersion: v2
name: bcc
description: A Helm chart for Kubernetes
type: application
version: "2024.02.00-0023-alpha"
appVersion: "1.0.0"
dependencies:
  - name: bcc-ui-chart
    repository: "https://pongsathorn-ph.github.io/bcc-ui/helm-chart/"
    version: "2024.02.00-0001-alpha"