apiVersion: v2
name: csc
description: A Helm chart for Kubernetes
type: application
version: "2024.02.00-0005-ALPHA"
appVersion: "1.0.0"
dependencies:
  - name: csc-ui-chart
    repository: "https://pongsathorn-ph.github.io/csc-ui/helm-chart/"
    version: "2024.02.00-0002-ALPHA"